### ISSUE TITLE
blandPowerCurve disagrees with Lu et al (2016)

### ISSUE THREAD

**Issue by rowannicholls** [arcaldwell49/SimplyAgree#44]
In Lu et al they have an example in Section 5 (which uses data published in Zhou et al) that gives an answer of n=83. Replicating that example with blandPowerCurve and find_n gives an answer of n=79. MedCalc also uses that example with the answer of n=83 (https://www.medcalc.org/manual/sample-size-bland-altman.php). I have a had a go at re-implementing the algorithm in Python but also get an answer of n=79, so I assume I am making the same mistake.

**Comment by arcaldwell49** [comment]
Hmm, interesting. I tested this function against PASS documentation (or that is what I remember). Issue is noted though and I will look into it within the next month. In the meantime can you post the example code that gives that result?

Thanks!

**Comment by rowannicholls** [comment]
Sure thing:

```
library(SimplyAgree)

powerCurve <- blandPowerCurve(
    samplesizes = seq(2, 200, 1),
    mu = 0.001167,
    SD = 0.001129,
    delta = 0.004,
    conf.level = 0.95,
    agree.level = 0.95
)
found_n <- find_n(powerCurve, power = 0.80)
n <- found_n[["N"]]
power <- found_n[["power"]]

print(c(n, power))  # [1] 79.0000000  0.8022956
```

From Lu et al:

![Screenshot from 2023-06-26 13-29-44](https://github.com/arcaldwell49/SimplyAgree/assets/29927605/6971626e-52b7-4a12-810c-3958471cfc31)

**Comment by arcaldwell49** [comment]
I will still look into this further, but just checked PASS's documentation. Again, I have based and checked my package on NCSS's PASS (which is typically considered the gold standard) so I'm leaning towards believing this is an error due to the Lu et al approximation.

See the following comment.

<img width="865" alt="Screenshot 2023-07-08 at 5 51 59 PM" src="https://github.com/arcaldwell49/SimplyAgree/assets/24322628/9ef43a22-8d61-46c1-8bc0-eac49e78ce77">
